### ISSUE TITLE
Images aren't loaded from live data from Google Places API

### ISSUE THREAD

**Issue by triceam** [IBM-MIL/CognitiveConcierge#10]
It looks like images are only loaded from mock data.  However, we can pull the generic google places `icon` field instead.  

It's not pretty, but better than the big white gap:
![image](https://cloud.githubusercontent.com/assets/974294/21063114/094f2118-be22-11e6-9e54-04b04334b615.png)

**Comment by bvennam** [comment]
Hey andy - we actually are pulling in images for live data.  I just ran to confirm.  However, if you don't give the client app your google api key, it won't pull in images... I wonder if that's what was going on?

I agree though that if no image gets pulled, we should put SOMETHING there.

**Comment by stevemar** [comment]
i believe this is fixed as images are being pulled in.
