### ISSUE TITLE
"Use legacy swift version" error when building in Xcode 8.2

### ISSUE THREAD

**Issue by dsullivan2** [IBM-MIL/CognitiveConcierge#12]
The latest repo has been updated to Swift 3, but does not build.  I get this error:

Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly

**Comment by beemarie** [comment]
@dsullivan2, Let's take a look -- Could you please tell me what version of xcode you are using?

**Comment by bvennam** [comment]
@dsullivan2 I'm taking a look now to try to recreate.

**Comment by glennrfisher** [comment]
Hi @dsullivan2. Are you experiencing this build error with the iOS application or the server application?

I wasn't able to recreate the issue with the iOS application. Here are the steps that I followed:
1. Cloned the `master` branch
2. Ran `carthage update --platform iOS`
3. Ran `pod install`
4. Built using Xcode 8.2.1.

If the build error you're experiencing is with the iOS application, then there's probably something different about our build environments. Here are a few things to check:

- Are you running the latest version of Xcode? I was able to build with Xcode 8.2.1 (8C1002).
- Is your repository up-to-date? In other words, are you sure you pulled the latest changes from the `master` branch when trying to build?
- Did you try cleaning the Xcode build folder? Sometimes past errors can linger unexpectedly. When I run into odd build errors, they can sometimes be fixed just by running the "Clean Build Folder" command. To do so, click on the "Product" menu in the menubar, then hold down the option key and select "Clean Build Folder...". It couldn't hurt to run the regular "Clean" command, too.

Hopefully that helps! If not, let us know and we'll continue following up to try and solve the issue.

**Comment by glennrfisher** [comment]
One more thing to try, @dsullivan2, is updating your CocoaPods installation. Some folks experienced a similar [issue](https://github.com/Alamofire/Alamofire/issues/1526) with Alamofire, which was resolved by cleaning the build folder and updating CocoaPods.

I am running `1.1.1`. To check the version of CocoaPods installed on your machine, run: `pod --version`.

To update CocoaPods, run the following command: `sudo gem install cocoapods`

**Comment by dsullivan2** [comment]
I worked after I updated to Xcode 8.2.1 (8C1002) and running "Clean Build Folder". Thank you!
