### ISSUE TITLE
Carthage update command fails while trying via brew 

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-MIL/CognitiveConcierge#14]
FYI..
The command : **carthage update --platform iOS** fails with an error show below post the **brew update** and **brew install carthage**. Works fine when carthage is installed via .pkg 

> dyld: Library not loaded: @rpath/CarthageKit.framework/CarthageKit
>   Referenced from: /usr/local/bin/carthage
>   Reason: image not found
> Abort trap: 6

May be the same issue mentioned in this [link](https://github.com/Carthage/Carthage/issues/304)

**Comment by cr2003** [comment]
carthage update --platform iOS fail with error: unterminated Git reference name "v0.14.2", I edited the Cartfile and remove the version, without reference version, by default it downloaded the latest version in my case "v.0.15.0" and it did the trick, compile and run OK.
