### ISSUE TITLE
Tutorial is flawed

### ISSUE THREAD

**Issue by erssykes** [IBM-MIL/CognitiveConcierge#20]
Trying to follow along in the tutorial:
https://github.com/IBM-MIL/CognitiveConcierge 

step:
4. Once the project is cloned, open up the .xcodeproj file that was created for you in ICT under Local Server Repository. Edit the Sources/restaurant-recommendations/main.swift file's Constants struct with your own Google API Key for Web.

Can't edit 'main.swift'   because it DOESN'T EXIST.

How can the tutorial be this far off?

It looks like there was an update a few days ago to the code.... don't they cross-check code updates to the actual tutorial so that they are in sync ?

Very frustrating and disappointing.

:(

**Comment by bvennam** [comment]
Hi @erssykes 

Thanks for reaching out!  Let's try to debug what's going on.

I just cloned the project, and main.swift does exist, at least for me...
![image](https://cloud.githubusercontent.com/assets/8460492/24315953/67a194ec-10b8-11e7-87a4-a85890b8a798.png)

You can also check it out online here:
https://github.com/IBM-MIL/CognitiveConcierge/blob/master/CognitiveConcierge-Server/Sources/main.swift 

Did you use ICT to clone the project?  What are you seeing differently in your cloned version of the project?

**Comment by bvennam** [comment]
My initial thought is that maybe something went wrong with the clone of the project.... I'll try to help you debug once we can see a few more details!

**Comment by erssykes** [comment]
Dear Belinda,

Thank you so much for your help!
I have been trying to get this working for quite some time.  https://developer.ibm.com/swift/2016/10/24/build-end-end-swift-app-watson-apis/

I’m hoping to demonstrate this to my students next week.  The course is Mobile Computing in our new degree (Bachelor of Applied Computer Science (Mobile Computing) at Sheridan College:
https://academics.sheridancollege.ca/programs/bachelor-of-applied-computer-science-mobile-computing

We are covering Swift App Dev and have covered some preliminary topics of IBM Watson.  Love to demonstrate how to create a simple iOS app in Swift that uses IBM Watson services.

I think you are right, the clone process may have failed, but unfortunately I didn’t get an error message to follow up on :(

I did use ICT to clone the project.  Here is mine:

[cid:3240C059-144B-4D04-BDD7-FF52A6B9977B]


I know notice that I’m also missing ‘Sources’. Which would explain why I was having problems trying to complete the following:

  *   Once the project is cloned, open up the .xcodeproj file that was created for you in ICT under Local Server Repository. Edit the Sources/restaurant-recommendations/Configuration.swift file’s Constants struct with your own Google API Key for Web.”

Under step 1 on:
https://developer.ibm.com/swift/2016/10/24/build-end-end-swift-app-watson-apis/


Help?

Thanks,
Ed Sykes
http://www-acad.sheridanc.on.ca/~sykes/






On Mar 24, 2017, at 6:37 PM, Belinda Vennam <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @erssykes<https://github.com/erssykes>

Thanks for reaching out! Let's try to debug what's going on.

I just cloned the project, and main.swift does exist, at least for me...
[image]<https://cloud.githubusercontent.com/assets/8460492/24315953/67a194ec-10b8-11e7-87a4-a85890b8a798.png>

You can also check it out online here:
https://github.com/IBM-MIL/CognitiveConcierge/blob/master/CognitiveConcierge-Server/Sources/main.swift

Did you use ICT to clone the project? What are you seeing differently in your cloned version of the project?

**Comment by bvennam** [comment]
I've sent you an email as well, but I think the correct next step would be for you to:
1) Delete the project.
2) Try another clone (using ICT).
3) Let me know how that goes.

If you're missing files, it does look like something failed during the clone.

Also, please ensure you're following the instructions from this github, rather than the blog.  I'll make sure I update the blog to note that as well.

**Comment by bvennam** [comment]
Closing this, as we made a few updates to the tutorial, and should work fine now.  Please reopen if you decide to use for your course next semester & run into any issues.  Thanks!

**Comment by erssykes** [comment]
Thanks Belinda!

Shall do

Kind Regards,
Ed


On May 12, 2017, at 7:27 PM, Belinda Vennam <notifications@github.com<mailto:notifications@github.com>> wrote:


Closing this, as we made a few updates to the tutorial, and should work fine now. Please reopen if you decide to use for your course next semester & run into any issues. Thanks!
