### ISSUE TITLE
carthage update --platform iOS fails

### ISSUE THREAD

**Issue by tedhogan-zz** [IBM-MIL/CognitiveConcierge#21]
carthage update --platform iOS . 

fails with....

error: underlying Objective-C module 'SpeechToTextV1' not found

**Comment by tedhogan-zz** [comment]
I updated the cartfile to use the latest swift-sdk version and now it works.

**Comment by bvennam** [comment]
@tedhogan thanks!  I just updated the app to work with the latest xcode (8.3) and swift (3.1) versions, along with updating to the latest swift-sdk version.
