### ISSUE TITLE
Dependency error when building server app

### ISSUE THREAD

**Issue by tedhogan-zz** [IBM-MIL/CognitiveConcierge#22]
When deploying the server app to Bluemix, the build fails with:
swift-package: error: The dependency graph could not be satisfied (https://github.com/IBM-Swift/LoggerAPI.git)Mar 31, 2017 4:06:08 PM

**Comment by shekooogames** [comment]
I have the same issues, tried adding the .Package(url: "https://github.com/IBM-Swift/LoggerAPI", majorVersion: 1), to Package.swift results in Failed to compile droplet and subsequent exit status 223. 
Help !

**Comment by tedhogan-zz** [comment]
Interestingly enough, the restaurant-reviews Xcode project has "LoggerAPI" as it's bundle identifier...

**Comment by bvennam** [comment]
@tedhogan @upwardstudios My guess is that you both were using the latest Xcode (8.3) & Swift (3.1) versions.  Yesterday, I updated the app & dependencies to work against these, and you should no longer see these errors.

Thanks!
