### ISSUE TITLE
Error com.ibm.watson.developer.cloudConversation

### ISSUE THREAD

**Issue by sunilkumarj** [IBM-MIL/CognitiveConcierge#27]
I have setup the ios project i am getting com.ibm.watson.developer-cloud.ConversationV1 Code=401 "Not Authorised" 

UserInfo = (NSLocalizedFailureReason = Not Authorized)

**Comment by bvennam** [comment]
Hi!  That potentially sounds like you are not providing the correct credentials for your Conversation Service instance on Bluemix.

Look in the CognitiveConcierge-iOS/CognitiveConcierge folder for the CognitiveConcierge.plist file.  Do you have the correct credentials supplied for the Conversation service?

**Comment by sunilkumarj** [comment]
Hi Belinda Vennam! I have given google place api key in plist file. I have install blue mix, I am not able to setup the server. Can you please help me for setup the server, I am new to blue mix.

**Comment by sunilkumarj** [comment]
Hi thanks. I am able to follow the instruction. 

update Cartfile with.
github "watson-developer-cloud/swift-sdk"

3rd point in the Blue Mix setup I got confusion. I have to select the downloaded from your repo or select sample application from blue mix.  

Vacations and shows. From where to pull for all the functionality. 

Can you please help me.

**Comment by bvennam** [comment]
Hi @sunilkumarj -- Vacation and shows does not have any functionality as this is actually just a starter app for you to get started and see how the various watson services work.
