### ISSUE TITLE
bluemix.plist - isLocal should be true

### ISSUE THREAD

**Issue by nathan-hekman** [IBM-MIL/CognitiveConcierge#3]
Should set isLocal to true to be consistent with TodoList sample also featured in ICT: https://github.com/IBM-Swift/TodoList-iOS/blob/e761edd5c1b433da9c63b8ae5cbac4296ccdf009/TodoList-iOS/Configuration/bluemix.plist

Currently it is set to be false, so the client app is targeting remote after local cloning/setup in ICT. This should be true so the user can target locally first without needing to change this field.

<img width="1019" alt="screen shot 2016-10-17 at 2 38 39 pm" src="https://cloud.githubusercontent.com/assets/6822736/19452651/6bdbb834-9477-11e6-95c0-7c5bb4ea7303.png">

**Comment by bvennam** [comment]
done.
