### ISSUE TITLE
jsqmessagesviewcontroller has been deprecated

### ISSUE THREAD

**Issue by dsullivan2** [IBM-MIL/CognitiveConcierge#32]
http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/
I hope other people will take over "official" support of this project.

**Comment by ljbennett62** [comment]
Thank you for sharing. We will update Cognitive Concierge

**Comment by stevemar** [comment]
Looks like we've been lucky in that JSQMessages hasn't bitten us yet, but it eventually will.  https://github.com/MessageKit/MessageKit/issues/1 looks like a good replacement. cc @tanmayb123
