### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by agmo-ios** [IBM-MIL/CognitiveConcierge#34]
Hi there,

After doing necessary carthage update and pod install, it shows compilation error.
![screen shot 2017-11-02 at 2 50 39 pm](https://user-images.githubusercontent.com/23096469/32313321-49eb09a4-bfdd-11e7-8016-d31b67dcd20e.png)

**Comment by stevemar** [comment]
tagging @beemarie to see if she can help out here. 

@beemarie you were fairly active in older issues for this repo, i'm hoping you can help us out again.

**Comment by stevemar** [comment]
This is working due to #59 and #60
