### ISSUE TITLE
deploy server application fails

### ISSUE THREAD

**Issue by ghost** [IBM-MIL/CognitiveConcierge#41]
Using 'deploy to bluemix'
the swift version requested is not the default in bluemix.

<img width="1723" alt="screen shot 2018-01-03 at 10 29 32 am" src="https://user-images.githubusercontent.com/27785752/34526746-6b292e2e-f071-11e7-93f7-6c4de9a22ec4.png">

**Comment by ghost** [comment]
Instructions for IBM Cloud Application Tools needs to be removed, because it's no longer being developed.

**Comment by scottdangelo** [comment]
This is still broken.

**Comment by stevemar** [comment]
@nching1969 instructions for ICAT were removed, this is still broken though...

**Comment by stevemar** [comment]
tagging @beemarie to see if she can help out here. 

@beemarie you were fairly active in older issues for this repo, i'm hoping you can help us out again.

**Comment by bvennam** [comment]
A couple of things going on here.
1) I was able to push the code with both the manual CLI process & the deploy to bluemix button.  It does show the warning about the Procfile or buildpack in the logs, but the app starts up fine. 

2) Bluemix UI appears to have a bug where it doesn't update the "running" & "not running" status unless you refresh the page.  Are you sure the app failed to deploy?  

3) Check the instructions I wrote for manually pushing the app using `bx app push` -- it asks the user to first update an API Key.  If the user uses the "deploy to bluemix" button to just magically push the code, that api key won't be updated & the server side code won't work.  I suppose they could click "deploy to bluemix," then update their code, and I guess depending on the pipeline it might trigger a re-push?

If the deploy to bluemix button is required please reach out to @ishangulhane while i'm away to confirm that the pipeline works in that way, as he looks to be the one who added it. https://github.com/IBM/CognitiveConcierge/commit/f4842f770f0e0779ea6410626d00f5644104e104

Is the deploy to bluemix button required?

4) @scottdangelo please provide some additional error messages to help debug.  The error messages from January are clearly out of date as the swift version is not 3.1.1.  I'm also unable to recreate as the app seems to be deploying fine.

**Comment by stevemar** [comment]
this is more or less working now due to #59 and #60
