### ISSUE TITLE
Pods are missing when running the IOS app.

### ISSUE THREAD

**Issue by Twanawebtech** [IBM-MIL/CognitiveConcierge#5]
When running the IOS app, I am getting this:
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

Include steps in ReadME to install pods. 

-------

This demo also been added under our Bluemix.github.io page: https://ibm-bluemix.github.io

**Comment by bvennam** [comment]
Hi Twanawebtech!  Thank you for your comment -- did you run pod install before running the iOS app?  There are some set up instructions that are included in the README for the app that you should follow to get the app set up.  Let us know whether that works for you or not....

**Comment by Twanawebtech** [comment]
@beemarie yes it worked for me now. 
sorted. 

Thanks.

**Comment by bvennam** [comment]
Wonderful!  Thank you... let me know if we can help you with anything else!
