### ISSUE TITLE
iOS Build failed due to SpeechRecognitionResults

### ISSUE THREAD

**Issue by Netholm2017work** [IBM-MIL/CognitiveConcierge#54]
After cloning and following the steps provided, the iOS build failed. I tried to look through some of the errors and i found in /Controllers/MessagesViewController/MessageViewModel on line 220. I get an error related to SpeechRecognitionResults. Specifically **results.bestTranscript**, looking through the documentation(https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/#recognize_sessionless_nonmp12) and scrolling down to SpeechRecognitionResults object. There is no **.bestTranscript**

Am i the only one who is having this problem?

**Comment by mkistler** [comment]
The `bestTranscript` is constructed by the SDK and is not actually part of the response from STT.  This support in the SDK was recently refactored into a separate class called `SpeechRecognitionResultsAccumulator`.  There is information in the README on how to use this class to construct a `bestTranscript`.

**Comment by Netholm2017work** [comment]
Thanks @mkistler for the response. I should have looked into the Swift SDK first.
