### ISSUE TITLE
Deploy to IBM Cloud button doesn't provision the required services

### ISSUE THREAD

**Issue by ptitzler** [IBM-MIL/CognitiveConcierge#56]
> The manifest.yml file [included in the repo] is parsed to obtain the name of the application, configuration details, and the list of services that should be provisioned. 
There are no services listed in `manifest.yml` and therefore no service instances are provisioned after deployment has completed. Looks like the instructions need to be updated.

**Comment by stevemar** [comment]
@tanmayb123 please fix, see https://github.com/IBM/watson-banking-chatbot/blob/master/manifest.yml as an example.

**Comment by tanmayb123** [comment]
Done
