### ISSUE TITLE
carthage update --platform iOS fails

### ISSUE THREAD

**Issue by ptitzler** [IBM-MIL/CognitiveConcierge#57]
Following the instructions

> From Terminal, change directories into the YourProjectName/CognitiveConcierge-iOS folder and run the following command to install the necessary dependencies (This may take some time):

this error is raised:
```
$ carthage update --platform iOS
*** Cloning swift-sdk
*** Cloning Starscream
*** Checking out Starscream at "3.0.5"
*** Checking out swift-sdk at "v0.29.0"
*** xcodebuild output can be found in /var/folders/cs/560yb9sn0xv9h_gw47z5l1140000gn/T/carthage-xcodebuild.W7WOKH.log
*** Downloading swift-sdk.framework binary at "v0.29.0"
*** Skipped building Starscream due to the error:
Dependency "Starscream" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/daltoniam/Starscream/issues/new
```

**Comment by stevemar** [comment]
@ptitzler are you running the latest version of carthage and xcode? 

We just got the travis job running successfully after much neglect, and we've tested things out locally and they are working. Please re-open if you're still seeing an error. cc @tanmayb123

**Comment by ptitzler** [comment]
Carthage was at version 0.30.1. After I upgraded XCode to 9.4.1 the problem went away!
