### ISSUE TITLE
Related Links are broken

### ISSUE THREAD

**Issue by ptitzler** [IBM-MIL/CognitiveConcierge#58]
In https://developer.ibm.com/code/patterns/build-a-cognitive-recommendation-app-with-swift/, the following *related links*  return  404:
 * Cognitive Conversation architecture
 * Swift@IBM — Kitura
 * IBM Swift Sandbox

**Comment by stevemar** [comment]
on it

**Comment by stevemar** [comment]
- I removed the `Cognitive Conversation architecture` link because the new arch center is `Cognitive for intelligence and insights from data`
- I removed `IBM Swift Sandbox` because I can't find one that's available
- I updated `Swift@IBM — Kitura` to https://www.kitura.io/
