### ISSUE TITLE
Image not found for AssistantV1 framework

### ISSUE THREAD

**Issue by tanmayb123** [IBM-MIL/CognitiveConcierge#64]
When you run the latest version, you will get the following error:

`dyld: Library not loaded: @rpath/AssistantV1.framework/AssistantV1
  Referenced from: /Users/tanmaybakshi/Library/Developer/CoreSimulator/Devices/A43DC0EF-27AD-4EE0-9F49-994C2E482ED8/data/Containers/Bundle/Application/7A2E5529-B725-48EB-8F76-99F678020532/CognitiveConcierge.app/CognitiveConcierge
  Reason: image not found`

Because of the conversationv1 to assistantv1 change.

**Comment by tanmayb123** [comment]
A temporary fix is to remove conversationv1.framework from the "linked frameworks and libraries" in xcode, and to add "assistantv1.framework" to that section as well as "embedded binaries"

**Comment by tanmayb123** [comment]
Fixed

**Comment by abhisheksahay** [comment]
assistantv1.framework is added, but still I have this issue
