### ISSUE TITLE
Carthage issue building the first time

### ISSUE THREAD

**Issue by triceam** [IBM-MIL/CognitiveConcierge#9]
Wouldn't build on my machine, with unhelpful `NSInternalInconsistencyException` error when running `carthage update --platform iOS` step.  

Tracked it down, and for some reason Carthage was pulling the wrong version of the Watson ios-sdk.  Changed Cartfile to this, and it fixed the build process:

```
# cartfile contents
github "watson-developer-cloud/ios-sdk" == 0.8.2
```

**Comment by bvennam** [comment]
thanks, this should be up to date.
